export { default as Home } from './home/Home'
export { default as Nav } from './nav/Nav'
export { default as Footer } from './footer/Footer'
export { default as About } from './about/About'
export { default as Plane } from './plane/Plane'
export { loader as planeLoader } from './plane/Plane'
export { default as Layout } from './layout/Layout'
export { default as Details } from './details/Details'
export { loader as detailsLoader } from './details/Details'
export { default as Dashboard } from './dashboard/Dashboard'
export { loader as dashBoard } from './dashboard/Dashboard'
export { default as Incomes } from './incomes/Incomes'
export { default as Reviews } from './reviews/Reviews'
export { default as Host } from './host/Host'
export { default as PlaneComp} from './planeComp/PlaneComp'
export { loader as planeCompLoader} from './planeComp/PlaneComp'
export { default as CompDetails } from './compDetails/CompDetails'
export { loader as compDetailsLoader } from './compDetails/CompDetails'
export { default as DetailsList } from './alldetails/DetailsList'
export { default as Pricing } from './alldetails/Pricing'
export { default as Photo } from './alldetails/Photo'
export { default as Error } from './error/Error'
export { default as Login } from './login/Login'
export { action as loginAction } from './login/Login'
export { loader as loginLoader } from './login/Login'
